/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("i2d.pp.prdorderissue.details.util.Formatters");jQuery.sap.require("i2d.pp.mrpcockpit.reuse.util.CommonFormatter");jQuery.sap.require("sap.ca.ui.model.format.NumberFormat");jQuery.sap.require("i2d.pp.prdorderissue.details.util.Constants");jQuery.sap.require("i2d.pp.mrpcockpit.reuse.util.CommonConstants");i2d.pp.prdorderissue.details.util.Formatters=function(){var m={};for(var k in i2d.pp.mrpcockpit.reuse.util.CommonFormatter){m[k]=i2d.pp.mrpcockpit.reuse.util.CommonFormatter[k]}return m}();
i2d.pp.prdorderissue.details.util.Formatters.formatFromToDateShort=function(s,e){if(s!==null&&e!==null&&s!==undefined&&e!==undefined){var d=sap.ui.core.format.DateFormat.getDateInstance({style:'short'});var a=d.format(s);var b=d.format(e);return i2d.pp.mrpcockpit.reuse.util.CommonFormatter.getTextPairWithDash.call(this,a,b)}return""};
i2d.pp.prdorderissue.details.util.Formatters.baseMaterialDelayText=function(l){if(l>=2){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_BASE_MAT_MISSING_X_DAYS",[l])}else if(l===1){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_BASE_MAT_MISSING_ONE_DAYS")}else{return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_BASE_MAT_MISSING_ON_TIME")}};
i2d.pp.prdorderissue.details.util.Formatters.baseMaterialDelayState=function(l){if(l>=2){return sap.ui.core.ValueState.Warning}else if(l===1){return sap.ui.core.ValueState.Warning}else{return sap.ui.core.ValueState.None}};
i2d.pp.prdorderissue.details.util.Formatters.baseMaterialDelayStateDetail=function(l){if(l>=2){return sap.ui.core.IconColor.Negative}else if(l===1){return sap.ui.core.IconColor.Negative}else{return sap.ui.core.IconColor.Default}};
i2d.pp.prdorderissue.details.util.Formatters.missingComponentsText=function(n){if(n>=2){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_X_COMPONENTS_MISSING",[n])}else if(n===1){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_ONE_COMPONENT_MISSING",[n])}else{return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_NO_MISSING_COMPONENTS",[n])}};
i2d.pp.prdorderissue.details.util.Formatters.missingComponentsState=function(n){if(n>=2){return sap.ui.core.ValueState.Warning}else if(n===1){return sap.ui.core.ValueState.Warning}else{return sap.ui.core.ValueState.None}};
i2d.pp.prdorderissue.details.util.Formatters.processDelayText=function(d){if(d>=2){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_DELAYED_BY_X_DAYS",[d])}else if(d===1){return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_DELAYED_BY_ONE_DAY")}else{return this.getModel('i18n').getResourceBundle().getText("MASTER_STATUS_ON_SCHEDULE")}};
i2d.pp.prdorderissue.details.util.Formatters.processDelayState=function(d){if(d>=2){return sap.ui.core.ValueState.Warning}else if(d===1){return sap.ui.core.ValueState.Warning}else{return sap.ui.core.ValueState.None}};
i2d.pp.prdorderissue.details.util.Formatters.detailTitle=function(s,m){switch(s){case i2d.pp.mrpcockpit.reuse.util.CommonConstants.MRP_ELEMENT_CATEGORY_PRDORD:return this.getModel('i18n').getResourceBundle().getText("DETAIL_TITLE_PROD",[m]);break;case i2d.pp.mrpcockpit.reuse.util.CommonConstants.MRP_ELEMENT_CATEGORY_PRCORD:return this.getModel('i18n').getResourceBundle().getText("DETAIL_TITLE_PROC",[m]);break;default:return this.getModel('i18n').getResourceBundle().getText("DETAIL_TITLE");break}};
i2d.pp.prdorderissue.details.util.Formatters.displayAreaOrPlant=function(m,a,b,c){if(a===""||a===c){return this.getModel('i18n').getResourceBundle().getText("DETAIL_MATERIAL_PLANT",[m,c])}else{return this.getModel('i18n').getResourceBundle().getText("DETAIL_MATERIAL_MRPAREA",[m,b,a])}};
i2d.pp.prdorderissue.details.util.Formatters.formatMilestoneConfirmation=function(i){if(i){return sap.ui.core.IconPool.getIconURI("map")}else{return null}};
i2d.pp.prdorderissue.details.util.Formatters.formatOperation=function(o,s){s=parseInt(s);if(s===0||isNaN(s)){return o}else{return this.getModel('i18n').getResourceBundle().getText("OPERATION_TITLE",[o,s])}};
i2d.pp.prdorderissue.details.util.Formatters.formatScheduledTimeState=function(i){return i===false?sap.ui.core.ValueState.None:sap.ui.core.ValueState.Error};
i2d.pp.prdorderissue.details.util.Formatters.formatMissingOperationQuantity=function(c,o,d){return i2d.pp.mrpcockpit.reuse.util.CommonFormatter.quantity(Math.max(o-c,0),d)};
i2d.pp.prdorderissue.details.util.Formatters.formatStatusText=function(s){var t;switch(s){case"I0001":t="CRTD_CREATED";break;case"I0002":t="REL_RELEASED";break;case"I0010":t="PCNF_PARTIALLY_CONFIRMED";break;case"I0009":t="CNF_CONFIRMED";break;default:return s}return this.getModel('i18n').getResourceBundle().getText(t)};
i2d.pp.prdorderissue.details.util.Formatters.formatStatusValue=function(s){switch(s){case"I0001":return 0;case"I0002":return 1;case"I0010":return 2;case"I0009":return 3}return 0};
i2d.pp.prdorderissue.details.util.Formatters.formatMilestoneOverdue=function(s){return s?1:0};
i2d.pp.prdorderissue.details.util.Formatters.formatMilestoneLabel=function(s){var t;switch(s){case"I0002":t="MS_REL_RELEASED";break;case"I0010":t="MS_PCNF_PARTIALLY_CONFIRMED";break;case"I0009":t="MS_CNF_CONFIRMED";break;case"I0012":t="MS_DLR_DELIVERED";break;default:return s}return this.getModel('i18n').getResourceBundle().getText(t)};
i2d.pp.prdorderissue.details.util.Formatters.formatMilestoneTooltip=function(s){var t;switch(s){case"I0002":t="MS_REL_RELEASED_TOOLTIP";break;case"I0010":t="MS_PCNF_PARTIALLY_CONFIRMED_TOOLTIP";break;case"I0009":t="MS_CNF_CONFIRMED_TOOLTIP";break;case"I0012":t="MS_DLR_DELIVERED_TOOLTIP";break;default:return s}return this.getModel('i18n').getResourceBundle().getText(t)};
i2d.pp.prdorderissue.details.util.Formatters.formatOpenPlannedQuantities=function(o,p,u,a){var O=i2d.pp.mrpcockpit.reuse.util.CommonFormatter.quantity(o,a);var P=i2d.pp.mrpcockpit.reuse.util.CommonFormatter.quantity(p,a);return this.getModel('i18n').getResourceBundle().getText('DETAIL_OPEN_PLANNED_QUAN',[O,u,P])};
i2d.pp.prdorderissue.details.util.Formatters.returnUnderscore=function(){return"_"};
